"""empty message

Revision ID: 5c00241c4f4e
Revises: 
Create Date: 2024-10-09 18:06:07.763539

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c00241c4f4e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Player',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Player_name'), 'Player', ['name'], unique=True)
    op.create_table('Match',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('player1_id', sa.Integer(), nullable=False),
    sa.Column('player2_id', sa.Integer(), nullable=False),
    sa.Column('winner_id', sa.Integer(), nullable=True),
    sa.Column('score', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['player1_id'], ['Player.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['player2_id'], ['Player.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['winner_id'], ['Player.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Match')
    op.drop_index(op.f('ix_Player_name'), table_name='Player')
    op.drop_table('Player')
    # ### end Alembic commands ###
